apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: tap-demos
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 10
  workshops:
    - name: tap-workshop
      expires: 60m
      orphaned: 20m
      capacity: 1
      reserved: 1